name: letselevatorneo
description: elevatorsimulatorneo
publish_to: 'none'
version: 1.0.1+8

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter

  # Firebase Analytics
  firebase_core: ^2.27.1
  firebase_analytics: ^10.8.10
  # App Icon
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  # HyperLink
  url_launcher: ^6.2.5
  # Font
  google_fonts: ^6.1.1
  # Text to Speech
  flutter_tts: ^4.0.2
  # Audio Player
  audioplayers: ^6.0.0
  # Vibration
  vibration: ^1.8.3
  # Game Center
  games_services: ^4.0.0
  # Connectivity
  connectivity_plus: ^6.0.1
  # Shared Preference
  shared_preferences: ^2.2.2
  # Admob
  google_mobile_ads: ^5.0.0
  app_tracking_transparency: ^2.0.4
  # env
  flutter_dotenv: ^5.1.0
  # MVVM
  hooks_riverpod: ^2.4.5
  flutter_hooks: ^0.20.5
  # Image
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  path_provider: ^2.1.2
  # Permission
  permission_handler: ^11.3.0

  # Localize
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # App Splash
  flutter_native_splash: ^2.4.0

flutter_icons:
  image_path: "assets/images/menu/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#f7b249"
  adaptive_icon_foreground: "assets/images/menu/appIcon.png"

flutter_native_splash:
  image: "assets/images/menu/appIcon.png"
  color: "#f7b249"
  android_12:
    image: "assets/images/menu/appIcon.png"
    icon_background_color: "#f7b249"
  web: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/elevator/
    - assets/images/room/
    - assets/images/menu/
    - assets/.env

  fonts:
    - family: teleIndicators
      fonts:
        - asset: assets/fonts/teleindicadores.ttf
    - family: cornerstone
      fonts:
        - asset: assets/fonts/cornerstone.ttf
    - family: noto
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
