name: letselevatorneo
description: elevatorsimulatorneo
publish_to: 'none'
version: 1.5.19+66

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  webview_flutter_android: ^4.9.1
  webview_flutter: ^4.13.0
  # Firebase Analytics
  firebase_core: ^3.15.2
  firebase_core_web: ^2.24.1
  firebase_analytics: ^11.6.0
  firebase_analytics_web: ^0.5.10+16
  firebase_app_check: ^0.3.2+10
  # App Icon
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  # Text to Speech
  flutter_tts: ^4.2.3
  # Audio Player
  just_audio: ^0.10.4
  # Vibration
  vibration: ^3.1.3
  # SharedPreference
  shared_preferences: ^2.5.3
  shared_preferences_web: ^2.4.3
  # Game Center
  games_services: ^4.1.1
  connectivity_plus: ^6.1.4
  # Admob
  google_mobile_ads: ^6.0.0
  app_tracking_transparency: ^2.0.6+1
  #env
  flutter_dotenv: ^5.2.1
  # HyperLink
  path: ^1.9.1
  url_launcher: ^6.3.2
  url_launcher_web: ^2.4.1
  #MVVM
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  # Image
  file_picker: ^10.2.4
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  path_provider: ^2.1.5
  # Permission
  permission_handler: ^12.0.1
  # App Splash
  flutter_native_splash: ^2.4.6

  # Localize
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_native_splash:
  image: "assets/icon/icon.png"
  color: "#F7B249"
  android_12:
    image: "assets/icon/icon_splash.png"
    icon_background_color: "#F7B249"
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/audios/
    - assets/images/
    - assets/images/button/
    - assets/images/elevator/
    - assets/images/room/
    - assets/images/menu/
    - assets/images/settings/
    - assets/.env
  fonts:
    #For title font
    - family: cornerstone
      fonts:
        - asset: assets/fonts/cornerstone.ttf
    #For English, Spanish, French font
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    #For Japanese font
    - family: notoJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Bold.ttf
    #For Chinese font
    - family: notoSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Bold.ttf
    #For Korean font
    - family: bmDohyeon
      fonts:
        - asset: assets/fonts/bm-dohyeon.regular.ttf
    #For dot number
    - family: lcd
      fonts:
        - asset: assets/fonts/5x8_lcd_hd44780u_a02.ttf
    #For digital number
    - family: dseg
      fonts:
        - asset: assets/fonts/DSEG7Classic-BoldItalic.ttf
    #For digital alphabet
    - family: letsgo
      fonts:
        - asset: assets/fonts/letsgodigital.ttf